# Generated by Django 4.1.7 on 2023-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_addcategory_options_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
